### ISSUE TITLE
VV - Impact page Updates

### ISSUE THREAD

**Issue by pratsajency** [ajency/Thisandthat#17]
http://www.videovolunteers.org/our-impact/
1. Place a Video slider, displaying the Videos under "Impact" category on top. The way we have on Homepage
2. On the sidebar, "IMPACT STORIES", display the "Featured image" and the Title of the Blog

![3455](https://cloud.githubusercontent.com/assets/3326712/5601752/dba26aa2-933c-11e4-92ae-bfa309b5cf71.png)

**Comment by amit0773** [comment]
@pratsajency this is done
