### ISSUE TITLE
VV - Change the order of the Videos displayed on Homepage

### ISSUE THREAD

**Issue by pratsajency** [ajency/Thisandthat#46]
Currently the sidebar video and main video are the same on Homepage.

Expected:
The sidebar should display the second last posted video
And slider should start with the 3rd last posted video
So that ideally, never same videos are displayed on the Homepage twice

![43434](https://cloud.githubusercontent.com/assets/3326712/6065784/1808ba4e-ad8e-11e4-87f2-d30202c598af.png)

**Comment by anujkhurana** [comment]
Can you please ensure mails are not sent to you for tasks and vv team
copies me in all emails.

Who is approving these tasks and their effort/cost?

Off desk. Sent from phone.

**Comment by jeromie** [comment]
@pratsajency changes made.
