### ISSUE TITLE
Logo for "Everest Metals Pvt Ltd Nigeria"

### ISSUE THREAD

**Issue by pratsajency** [ajency/Thisandthat#49]
Create a Logo which just has text with the name "Everest Metals Pvt Ltd Nigeria" nicely placed in it.

**Comment by pratsajency** [comment]
@kashclay 
Do not spend more than 30 mins on this task plz.

**Comment by anujkhurana** [comment]
Logo will just be for Everest Metals. Logo's dont have pvt ltd in it.

**Comment by anujkhurana** [comment]
It's not even a logo. Please dont call it a logo. It is the text Everest
Metals written nicely in Photoshop. Not a logo project so don't need to do
any thinking or designing. Send something and we will use it.

**Comment by pratsajency** [comment]
Done.

![everest metals pvt ltd nigeria 1](https://cloud.githubusercontent.com/assets/3326712/6126351/c5b6f290-b145-11e4-9662-8e9adfcd49e2.jpg)

**Comment by avantih** [comment]
![everest_metals](https://cloud.githubusercontent.com/assets/1956317/6142837/896c3e9a-b1e4-11e4-98e8-2d925442ebe9.jpg)
![everest_metals_nigeria](https://cloud.githubusercontent.com/assets/1956317/6142838/896e4b54-b1e4-11e4-9d6c-a171d2489717.jpg)

**Comment by avantih** [comment]
Let's use Everest Metals Nigeria

**Comment by pratsajency** [comment]
Done - https://www.facebook.com/Everest.Metals.Pvt.Ltd.Nigeri
